from __future__ import annotations

# TLDs that are listed in the IANA RDAP bootstrap but whose registries
# block both RDAP (403 Forbidden) and WHOIS (connection reset) queries.
# Kept here for reference so we don't re-add them to the registry.

UNSUPPORTED_TLDS: list[str] = [
    # RDAP 403 + WHOIS connection reset
    "accountant",
    "adult",
    "bank",
    "baseball",
    "basketball",
    "beer",
    "bible",
    "bid",
    "biz",
    "blackfriday",
    "boston",
    "buzz",
    "casa",
    "catholic",
    "club",
    "compare",
    "cooking",
    "courses",
    "cpa",
    "cricket",
    "date",
    "design",
    "download",
    "earth",
    "faith",
    "fashion",
    "film",
    "fishing",
    "fit",
    "garden",
    "gay",
    "horse",
    "ink",
    "insurance",
    "krd",
    "law",
    "loan",
    "luxe",
    "men",
    "menu",
    "miami",
    "moe",
    "nyc",
    "one",
    "osaka",
    "party",
    "photo",
    "physio",
    "porn",
    "racing",
    "review",
    "rodeo",
    "rugby",
    "safety",
    "science",
    "select",
    "sex",
    "stream",
    "study",
    "sucks",
    "surf",
    "sydney",
    "taipei",
    "tattoo",
    "trade",
    "tv",
    "vip",
    "vodka",
    "voting",
    "webcam",
    "wedding",
    "wiki",
    "win",
    "work",
    "xxx",
    "yoga",
    # RDAP 403 + no WHOIS server at all
    "health",
    # RDAP connection failed + WHOIS timeout
    "cm",
    "ng",
]
